### ISSUE TITLE
RaspberyPi - armhf - ImportError: dynamic module does not define module export function (PyInit_zebra_scanner)

### ISSUE THREAD

**Issue by SMAkhup** [dayjaby/zebra-scanner#18]
Hi, after following the standard pip(3) installation I have a problem with importing the modules. I've tried global scope and python venvs. I've also tried both Python2 and Python3 and I keep getting the same result. May I ask for any suggestions?

I am sure I have the correct cpp SDK installed as I am able to run cpp apps with the scanner.

![image](https://user-images.githubusercontent.com/60701953/115878182-8a4f8580-a448-11eb-85ea-432a60fbfc18.png)

**Comment by dayjaby** [comment]
Hey @SMAkhup . Can you install zebra_scanner not via pip, but via `python3 setup.py install`? The pip version is not up-to-date.

**Comment by dayjaby** [comment]
Updated zebra_scanner on pypi so that pip install should work again now.
