### ISSUE TITLE
can not install on windows file path to long

### ISSUE THREAD

**Issue by HarryConings** [dayjaby/zebra-scanner#25]
Hi,
i have following problem with Pip install

 error: could not create 'build\temp.win-amd64-3.9\Release\Users\harryconings\AppData\Local\Temp\pip-install-wha9fj6l\zebra-scanner_d19889814d26433f8983a0694fad557c\src': De bestandsnaam of -extensie is te lang
De bestandsnaam of -extensie is te lang == FileName or extension to long

pip install zebra-scanner
Collecting zebra-scanner
  Using cached zebra-scanner-0.2.5.tar.gz (8.9 kB)
Building wheels for collected packages: zebra-scanner
  Building wheel for zebra-scanner (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\ProgramData\Anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\harryconings\\AppData\\Local\\Temp\\pip-install-wha9fj6l\\zebra-scanner_d19889814d26433f8983a0694fad557c\\setup.py'"'"'; __file__='"'"'C:\\Users\\harryconings\\AppData\\Local\\Temp\\pip-install-wha9fj6l\\zebra-scanner_d19889814d26433f8983a0694fad557c\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\harryconings\AppData\Local\Temp\pip-wheel-7647kebq'
       cwd: C:\Users\harryconings\AppData\Local\Temp\pip-install-wha9fj6l\zebra-scanner_d19889814d26433f8983a0694fad557c\
  Complete output (18 lines):
  C:\ProgramData\Anaconda3\lib\site-packages\setuptools\dist.py:487: UserWarning: Normalizing 'v0.2.5' to '0.2.5'
    warnings.warn(tmpl.format(**locals()))
  running bdist_wheel
  running build
  running build_ext
  building 'zebra_scanner' extension
  creating build
  creating build\temp.win-amd64-3.9
  creating build\temp.win-amd64-3.9\Release
  creating build\temp.win-amd64-3.9\Release\Users
  creating build\temp.win-amd64-3.9\Release\Users\harryconings
  creating build\temp.win-amd64-3.9\Release\Users\harryconings\AppData
  creating build\temp.win-amd64-3.9\Release\Users\harryconings\AppData\Local
  creating build\temp.win-amd64-3.9\Release\Users\harryconings\AppData\Local\Temp
  creating build\temp.win-amd64-3.9\Release\Users\harryconings\AppData\Local\Temp\pip-install-wha9fj6l
  creating build\temp.win-amd64-3.9\Release\Users\harryconings\AppData\Local\Temp\pip-install-wha9fj6l\zebra-scanner_d19889814d26433f8983a0694fad557c
  creating build\temp.win-amd64-3.9\Release\Users\harryconings\AppData\Local\Temp\pip-install-wha9fj6l\zebra-scanner_d19889814d26433f8983a0694fad557c\src
  error: could not create 'build\temp.win-amd64-3.9\Release\Users\harryconings\AppData\Local\Temp\pip-install-wha9fj6l\zebra-scanner_d19889814d26433f8983a0694fad557c\src': De bestandsnaam of -extensie is te lang
  ----------------------------------------
  ERROR: Failed building wheel for zebra-scanner

**Comment by dayjaby** [comment]
Windows won't be supported.
