### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by JapSeyz** [dayjaby/zebra-scanner#3]
Hey, I am trying to get this up and running, but I am running into a missing dependency: `CsIEventListenerXml.h`
```
japseyz@DESKTOP-649L0EF:~$ sudo pip install zebra-scanner
The directory '/home/japseyz/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/japseyz/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting zebra-scanner
  Downloading https://files.pythonhosted.org/packages/62/11/73f072f62cf5ee3bbfd6f20feada6a6350442c49dc826ea1865b98f47b38/zebra-scanner-0.2.3.tar.gz
Installing collected packages: zebra-scanner
  Running setup.py install for zebra-scanner ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ZRL8vJ/zebra-scanner/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-2j9GbK/install-record.txt --single-version-externally-managed --compile:
    /usr/local/lib/python2.7/dist-packages/setuptools/dist.py:470: UserWarning: Normalizing 'v0.2.3' to '0.2.3'
      normalized_version,
    running install
    running build
    running build_ext
    building 'zebra_scanner' extension
    creating build
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/tmp
    creating build/temp.linux-x86_64-2.7/tmp/pip-install-ZRL8vJ
    creating build/temp.linux-x86_64-2.7/tmp/pip-install-ZRL8vJ/zebra-scanner
    creating build/temp.linux-x86_64-2.7/tmp/pip-install-ZRL8vJ/zebra-scanner/src
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-3hk45v/python2.7-2.7.15~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/zebra-scanner -I/usr/include/python2.7 -I/tmp/pip-install-ZRL8vJ/zebra-scanner/src -I/usr/include/python2.7 -c /tmp/pip-install-ZRL8vJ/zebra-scanner/src/BoostPythonCoreScanner.cpp -o build/temp.linux-x86_64-2.7/tmp/pip-install-ZRL8vJ/zebra-scanner/src/BoostPythonCoreScanner.o -Wno-deprecated -std=c++0x
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from /tmp/pip-install-ZRL8vJ/zebra-scanner/src/BoostPythonCoreScanner.cpp:1:0:
    /tmp/pip-install-ZRL8vJ/zebra-scanner/src/BoostPythonCoreScanner.h:13:10: fatal error: CsIEventListenerXml.h: No such file or directory
     #include "CsIEventListenerXml.h"
              ^~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ZRL8vJ/zebra-scanner/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-2j9GbK/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-ZRL8vJ/zebra-scanner/
```

I am running Ubuntu 18.04 inside a Windows WSL binding.

**Comment by JapSeyz** [comment]
Sorry, I didn't know I had to install the Zebra SDK prior to downloading this.

https://www.zebra.com/us/en/support-downloads/software/developer-tools/scanner-sdk-for-linux.html

**Comment by dayjaby** [comment]
It's working now?

**Comment by JapSeyz** [comment]
Still had some issues but no longer with the dependencies. I'll try to investigate it during the weekend.

**Comment by dayjaby** [comment]
Okay, nice. Let me know if you have any other issues. Or if you also want to use some parts of the zebra SDK that's not included in this python package yet, feel free to implement them and send pull requests ;)

**Comment by 8722043447** [comment]
pip install zebra-scanner
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting zebra-scanner
  Using cached https://files.pythonhosted.org/packages/62/11/73f072f62cf5ee3bbfd6f20feada6a6350442c49dc826ea1865b98f47b38/zebra-scanner-0.2.3.tar.gz
Installing collected packages: zebra-scanner
  Running setup.py install for zebra-scanner ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\python27\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\\users\\username\\appdata\\local\\temp\\pip-install-rkar_4\\zebra-scanner\\setup.py'"'"'; __file__='"'"'c:\\users\\username\\appdata\\local\\temp\\pip-install-rkar_4\\zebra-scanner\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'c:\users\username\appdata\local\temp\pip-record-7zyv5_\install-record.txt' --single-version-externally-managed --compile
         cwd: c:\users\username\appdata\local\temp\pip-install-rkar_4\zebra-scanner\
    Complete output (20 lines):
    c:\python27\lib\site-packages\setuptools\dist.py:472: UserWarning: Normalizing 'v0.2.3' to '0.2.3'
      normalized_version,
    running install
    running build
    running build_ext
    building 'zebra_scanner' extension
    creating build
    creating build\temp.win-amd64-2.7
    creating build\temp.win-amd64-2.7\Release
    creating build\temp.win-amd64-2.7\Release\users
    creating build\temp.win-amd64-2.7\Release\users\username
    creating build\temp.win-amd64-2.7\Release\users\username\appdata
    creating build\temp.win-amd64-2.7\Release\users\username\appdata\local
    creating build\temp.win-amd64-2.7\Release\users\username\appdata\local\temp
    creating build\temp.win-amd64-2.7\Release\users\username\appdata\local\temp\pip-install-rkar_4
    creating build\temp.win-amd64-2.7\Release\users\username\appdata\local\temp\pip-install-rkar_4\zebra-scanner
    creating build\temp.win-amd64-2.7\Release\users\username\appdata\local\temp\pip-install-rkar_4\zebra-scanner\src
    C:\Users\username\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -I/usr/include/zebra-scanner -I/usr/include/python2.7 -Ic:\users\username\appdata\local\temp\pip-install-rkar_4\zebra-scanner\src -Ic:\python27\include -Ic:\python27\PC /Tpc:\users\username\appdata\local\temp\pip-install-rkar_4\zebra-scanner\src\BoostPythonCoreScanner.cpp /Fobuild\temp.win-amd64-2.7\Release\users\username\appdata\local\temp\pip-install-rkar_4\zebra-scanner\src\BoostPythonCoreScanner.obj -Wno-deprecated -std=c++0x
    cl : Command line error D8021 : invalid numeric argument '/Wno-deprecated'
    error: command 'C:\\Users\\username\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\python27\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\\users\\username\\appdata\\local\\temp\\pip-install-rkar_4\\zebra-scanner\\setup.py'"'"'; __file__='"'"'c:\\users\\username\\appdata\\local\\temp\\pip-install-rkar_4\\zebra-scanner\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'c:\users\username\appdata\local\temp\pip-record-7zyv5_\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.


i am getting above error when trying to install on windows10 pc

**Comment by dayjaby** [comment]
Did you install the zebra sdk? I only tested it on ubuntu.

**Comment by 8722043447** [comment]
i installed scanner sdk for windows  on my windows pc

**Comment by PeterVajda2** [comment]
Hi!

I am trying to compile the thing on windows 10, but:

> CsIEventListenerXml.h: No such file or directory

I installed zebra SDK both 32-bit and 64-bit, still cannot find the file. Any ideas, please?

Thank you!

**Comment by dayjaby** [comment]
See https://github.com/dayjaby/zebra-scanner/pull/2

I do not wanna merge this file due to licensing issues

**Comment by sohamshah93** [comment]
> pip install zebra-scanner
> DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
> Collecting zebra-scanner
> Using cached https://files.pythonhosted.org/packages/62/11/73f072f62cf5ee3bbfd6f20feada6a6350442c49dc826ea1865b98f47b38/zebra-scanner-0.2.3.tar.gz
> Installing collected packages: zebra-scanner
> Running setup.py install for zebra-scanner ... error
> ERROR: Command errored out with exit status 1:
> command: 'c:\python27\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\users\username\appdata\local\temp\pip-install-rkar_4\zebra-scanner\setup.py'"'"'; **file**='"'"'c:\users\username\appdata\local\temp\pip-install-rkar_4\zebra-scanner\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' install --record 'c:\users\username\appdata\local\temp\pip-record-7zyv5_\install-record.txt' --single-version-externally-managed --compile
> cwd: c:\users\username\appdata\local\temp\pip-install-rkar_4\zebra-scanner
> Complete output (20 lines):
> c:\python27\lib\site-packages\setuptools\dist.py:472: UserWarning: Normalizing 'v0.2.3' to '0.2.3'
> normalized_version,
> running install
> running build
> running build_ext
> building 'zebra_scanner' extension
> creating build
> creating build\temp.win-amd64-2.7
> creating build\temp.win-amd64-2.7\Release
> creating build\temp.win-amd64-2.7\Release\users
> creating build\temp.win-amd64-2.7\Release\users\username
> creating build\temp.win-amd64-2.7\Release\users\username\appdata
> creating build\temp.win-amd64-2.7\Release\users\username\appdata\local
> creating build\temp.win-amd64-2.7\Release\users\username\appdata\local\temp
> creating build\temp.win-amd64-2.7\Release\users\username\appdata\local\temp\pip-install-rkar_4
> creating build\temp.win-amd64-2.7\Release\users\username\appdata\local\temp\pip-install-rkar_4\zebra-scanner
> creating build\temp.win-amd64-2.7\Release\users\username\appdata\local\temp\pip-install-rkar_4\zebra-scanner\src
> C:\Users\username\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -I/usr/include/zebra-scanner -I/usr/include/python2.7 -Ic:\users\username\appdata\local\temp\pip-install-rkar_4\zebra-scanner\src -Ic:\python27\include -Ic:\python27\PC /Tpc:\users\username\appdata\local\temp\pip-install-rkar_4\zebra-scanner\src\BoostPythonCoreScanner.cpp /Fobuild\temp.win-amd64-2.7\Release\users\username\appdata\local\temp\pip-install-rkar_4\zebra-scanner\src\BoostPythonCoreScanner.obj -Wno-deprecated -std=c++0x
> cl : Command line error D8021 : invalid numeric argument '/Wno-deprecated'
> error: command 'C:\Users\username\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe' failed with exit status 2
> ----------------------------------------
> ERROR: Command errored out with exit status 1: 'c:\python27\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\users\username\appdata\local\temp\pip-install-rkar_4\zebra-scanner\setup.py'"'"'; **file**='"'"'c:\users\username\appdata\local\temp\pip-install-rkar_4\zebra-scanner\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' install --record 'c:\users\username\appdata\local\temp\pip-record-7zyv5_\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.
> 
> i am getting above error when trying to install on windows10 pc

I am also getting the same error @dayjaby
