### ISSUE TITLE
pyinstaller

### ISSUE THREAD

**Issue by MehmetEminMizrak** [dayjaby/zebra-scanner#31]
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tamirtakip.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

**Comment by dayjaby** [comment]
You mention only PyQt relevant warnings. Any issue with the zebra-scanner library?
