### ISSUE TITLE
Question regarding to zebra-scanner sdk

### ISSUE THREAD

**Issue by manhha1402** [dayjaby/zebra-scanner#4]
Hi,
Thank you for nice work.
I am getting a problem with the SDK installed from the debian package. I compile a sample provided by the SDK and get the error:
```
undefined reference to `ExecCommand(unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, StatusID*)
```
Seem like it can not find the linker dependencies. Do you have any idea? 
Thank you.

**Comment by dayjaby** [comment]
Hey,

thanks for trying out the code. Did you install the official zebra sdk? Looks like it is missing.

Cheers
David

**Comment by manhha1402** [comment]
Hi,
Thank for quick reply. 
I installed official Zebra SDK using debian package:
https://www.zebra.com/us/en/support-downloads/software/developer-tools/scanner-sdk-for-linux.html
I also tried Installation_Verify_Application.zip but it did not work.

**Comment by manhha1402** [comment]
Or if you have the old Zebra SDK from your local machine. Could you please upload it? Maybe they changed something in new version and something is missing. I am writing the ROS wrapper for the Zebra scanner
Thanks

**Comment by manhha1402** [comment]
It works now. I have to build the SDK from source file. Something is wrong from provided debian packages.
Thanks
