### ISSUE TITLE
Would you add support for windows?

### ISSUE THREAD

**Issue by bashar-tom** [dayjaby/zebra-scanner#5]

**Comment by Archloy** [comment]
Did you try to install on windows ? I'm currently installing Visual C++ (required by pip install zebra-scanner). Did you pass this step and have issues ? (the setup.py file say "os independent") 
If working after build, a python package including windows dll build will be appreciate.

**Comment by Archloy** [comment]
I'm unable to build this package, need to patch setup.py, egg/sources.txt and then dependencies seems missing. I don't have time to debug and project seems dead...

**Comment by dayjaby** [comment]
I won't add support for windows as I don't see a reason to integrate a barcode scanner in any windows computers. If you need it, feel free to make it work on your own.
