### ISSUE TITLE
Error in raspberry: 'zebra_scanner.Scanner' object has no attribute '__dict__'

### ISSUE THREAD

**Issue by unarix** [dayjaby/zebra-scanner#9]
Hello! After install the SDK an follow the instrucctions in the home page i get this error: 

![raspberry](https://user-images.githubusercontent.com/44549089/85760941-aed3b780-b6e8-11ea-9dda-39c9b994cc35.png)

AttributeError: 'zebra_scanner.Scanner' object has no attribute '__dict__'

Im trying to use a scanner symbol ds9208 in a raspberry pi1. Any help is apreciated.

**Comment by dayjaby** [comment]
Hey @unarix , can you try the changes made in #6 ?

**Comment by unarix** [comment]
solved!
